### ISSUE TITLE
Error installing `debugger` on ruby 2.1

### ISSUE THREAD

**Issue by infojunkie** [meedan/lapis#1]
Getting an error trying to install `debugger` gem, as described here: http://stackoverflow.com/questions/24395453/gem-install-debugger-error

I changed it to `byebug` and install succeeded.

**Comment by caiosba** [comment]
The `debugger` gem is added by `rails` itself, not by the template, and depends on the `rails` version. So it might be an issue with the lapis-based application that you used.

**Comment by caiosba** [comment]
Anyway, I changed the template to replace `debugger` by `byebug`.
