### ISSUE TITLE
Generate client library for multiple programming languages

### ISSUE THREAD

**Issue by infojunkie** [meedan/lapis#5]
Support the following languages:
- PHP
  - using [Guzzle](https://github.com/guzzle/guzzle) as HTTP client
  - using Composer as package manager
- Node.js 
  - using [SuperAgent](https://github.com/visionmedia/superagent) as HTTP client
  - using npm as package manager

**Comment by infojunkie** [comment]
I'm currently working on PHP generator

**Comment by infojunkie** [comment]
We should evaluate [swagger-codegen](https://github.com/swagger-api/swagger-codegen) instead of writing and maintaining these client generators. Just need to make sure it supports the features we need:
- tests
- mocks
- logging

**Comment by caiosba** [comment]
Great!

**Comment by infojunkie** [comment]
Closing in favour of explicit `swagger-codegen` issue.
