### ISSUE TITLE
The Ruby client methods should expand the parameters

### ISSUE THREAD

**Issue by caiosba** [meedan/lapis#8]
Right now, the client methods generated by Lapis are like this:

`def get_some_information(host, token, params)`
`end`
`...`
`get_some_information(host, token, {param1: value1, param2: value2, ..., param<n>: value<n>})`

It would be more intuitive to generate something like:

`def get_some_information(host, token, param1, param2, ..., param<n>)`
`end`
`...`
`get_some_information(host, token, value1, value2, ..., value<n>)`

**Comment by infojunkie** [comment]
On the PHP client side, the host and token are declared when instantiating the client only, and don't need to be passed to each subsequent call.

**Comment by infojunkie** [comment]
If we go for https://github.com/meedan/lapis/issues/12 first, we no longer need to do this, since `swagger-codegen` will be responsible for generating the Ruby client.

**Comment by infojunkie** [comment]
Closing in favour of #13.
